version: "3"
services:
 web:
   build: php-apache
   ports:
    - "80:80"
   volumes:
    - ${PHP_APACHE_DIRECTORY}:/var/www/html

 db:
  build: mysql
  ports:
   - "3306:3306"
  volumes:
   - ${DB_DIRECTORY}:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${DB_MYSQL_USER}
    MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
  #  - /home/ubuntu/codeigniter-project/mydatabase/:/var/lib/mysql